release:
  title-prefix: 'v'
  initial-version: '0.0.1'
  tag-prefix: 'v'
branch:
  version-branch-prefix: 'v'
  bump-version-commit-prefix: 'v'
categories:
  - title: 'Features:'
    labels:
      - 'Feature'
    commits:
      - 'feature:'
      - 'feat:'
    changes-prefix: ':gift: '

  - title: 'Bugfixes and Improvements:'
    labels:
      - 'Bug'
    commits:
      - 'fix'
    changes-prefix: ':ambulance: '

  - title: 'Locales:'
    commits:
      - 'locale'

  - title: 'Other:'
    commits:
      - 'chore'
      - 'refactor'
bump:
  default: 'patch'
  major:
    labels:
      - 'BreakingChange'
    commits:
      - 'breaking:'
  minor:
    labels:
      - 'Feature'
    commits:
      - 'feature:'
      - 'feat:'
files:
  - file-path: 'package.json'
    line: 3
  - file-path: 'package-lock.json'
    line: 3
