# Configuration for Label Actions - https://github.com/dessant/label-actions

not on Github:
  issues:
    comment: |
      Ahoi!

      It looks like this ticket is a request for help (or similar).
      Many helpful people will not see your message here and you are
      unlikely to get a useful response.

      We use github to handle bugreports, feature requests and
      planning new releases.

      Please use our Discord-Server for help: [discord.gg/mainsail](https://discord.gg/mainsail)

      This ticket will be automatically closed.

      Fair wind and a following sea!
      ~ Your friendly MainsailGithubBot

      *PS: I'm just an automated script, not a real sailor.*
    close: true

stale:
  prs:
    comment: |
      Ahoi!

      It looks like there hasn't been any recent updates on
      this pull request. If you created this pull request and
      no longer consider it to get merged, then please login
      to github and close it. Otherwise, if there is no further
      activity on this pull request, it will be automatically
      closed within the next 7 days.

      Fair wind and a following sea!
      ~ Your friendly MainsailGithubBot

      *PS: I'm just an automated script, not a real sailor.*
    close: true

-stale:
  prs:
    reopen: true
