# configuration file for git-cliff (0.1.0)

[changelog]
# changelog header
header = """
<!-- THIS FILE IS UPDATED AUTOMATICALLY, ANY CHANGES WILL BE OVERRIDDEN -->
# Changelog
All notable changes to Mainsail will be documented in this file.\n
"""
# template for the changelog body
# https://tera.netlify.app/docs/#introduction
body = """
{% if version %}\
    ## [{{ version | trim_start_matches(pat="v") }}](https://github.com/mainsail-crew/mainsail/releases/tag/{{version}}) - {{ timestamp | date(format="%Y-%m-%d") }}    
\
{% else %}\
    ## [unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}\
    ### {{ group | upper_first }}
    {% for commit in commits
    | filter(attribute="scope")
    | sort(attribute="scope") %}
        - **{{commit.scope}}**: {{ commit.message | upper_first | trim }} | [{{ commit.id | truncate(length=7, end="") }}]({{ commit.id }})\
        {%- if commit.breaking %}
        {% raw %}  {% endraw %}- **BREAKING**: {{commit.breaking_description}}
        {%- endif -%}

    {%- endfor -%}
    {%- for commit in commits %}
        {%- if commit.scope -%}
        {% else -%}
        {% raw %}\n{% endraw %}\
        - {{ commit.message | upper_first | trim }} | [{{ commit.id | truncate(length=7, end="") }}]({{ commit.id }})\
        {%- if commit.breaking %}
        {% raw %}  {% endraw %}- **BREAKING**: {{commit.breaking_description}}
        {%- endif -%}

        {% endif -%}
    {% endfor -%}
    {% raw %}\n{% endraw %}
{% endfor %}\n\
"""
# remove the leading and trailing whitespaces from the template
trim = true
# changelog footer
footer = """
"""

[git]
# allow only conventional commits
# https://www.conventionalcommits.org
conventional_commits = true
filter_unconventional = false
# regex for parsing and grouping commits
commit_parsers = [
    { message = "^docs\\(changelog\\):", group = "Changelog", skip = true}, # Old redundant commits
    { message = "^feat(\\(.*\\))?:", group = "Features"},
    { message = "^feature(\\(.*\\))?:", group = "Features"},
    { message = "^fix(\\(.*\\))?:", group = "Bug Fixes"},
    { message = "^docs(\\(.*\\))?:", group = "Documentation"},
    { message = "^perf(\\(.*\\))?:", group = "Performance"},
    { message = "^refactor(\\(.*\\))?:", group = "Refactor"},
    { message = "^style(\\(.*\\))?:", group = "Styling"},
    { message = "^test(\\(.*\\))?:", group = "Testing"},
    { message = "^locale(\\(.*\\))?:", group = "Localization"},
    { message = "^chore(\\(.*\\))?:", group = "Miscellaneous Tasks", skip = true}, # chore tasks are not relevant for the changelog
    { body = ".*security", group = "Security"},
    { message = "release v2.1.2", group = "Release"}, # workaround for v2.1.2 release
]
# filter out the commits that are not matched by commit parsers
filter_commits = true
ignore_tags="v*-(beta|rc)*"
# glob pattern for matching git tags
tag_pattern = "v[0-9]*"
