name: Bug report
description: You found an issue while using Mainsail? Report it here!
labels: ['⚡ Type: Bug']
body:
  - type: markdown
    attributes:
      value: >-
        ## ✨ First of all: Thank you for choosing Mainsail! ✨

        #### This form is ONLY for reporting issues and bugs related to Mainsail! 

        * In case you want to make a feature request, please use the following
        form: [Feature
        request](https://github.com/mainsail-crew/mainsail/issues/new?assignees=&labels=feature+request&template=feature_request.yml)

        * If you need general support, please visit us on
        [Discord](https://discord.gg/mainsail)

        ---
  - type: input
    id: version
    attributes:
      label: 'Mainsail Version:'
      description: Mainsail version where the issue occurs
      placeholder: <your current mainsail version>
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: 'Browser:'
      description: Which browser did you use when the issue occured?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other (Please tell us below)
    validations:
      required: true
  - type: dropdown
    id: device
    attributes:
      label: 'Device:'
      description: What kind of device did you use when the issue occured?
      options:
        - Desktop PC
        - Laptop
        - Mobile device (Phone, Tablet or similar)
        - Other (Please tell us below)
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: 'Operating System:'
      description: Which operating system runs on the device?
      options:
        - Windows
        - macOS
        - Linux
        - Android
        - iOS
        - Other (Please tell us below)
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: 'What happened?'
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: 'What did you expect to happen instead?'
      description: A clear and concise description of what you expected to happen instead.
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: 'How to reproduce this bug?'
      description: A clear description with precise steps to reproduce this bug.
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: 'Additional information:'
      description: |
        If you have any additional information for us or the options to choose from didn't suit your case, use the field below.
        Please note, you can also attach screenshots or screen recordings which help to display/describe the issue.
