// @ts-nocheck
// GENERATED by scripts/build-grammars.mjs from gcode.grammar — do not edit.
// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  ParamValue = 1,
  MessageText = 2,
  BareParamWord = 3,
  Program = 4,
  LineComment = 5,
  Message = 6,
  MessageCommand = 7,
  Param = 8,
  MacroName = 9,
  Operator = 10,
  String = 11,
  Number = 12,
  ParamWord = 13,
  Command = 14
