// @ts-nocheck
// GENERATED by scripts/build-grammars.mjs from gcode.grammar — do not edit.
// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {paramValue, messageText, bareParamWord} from "./gcode.tokens"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!dQVQ[OOOqQ^O'#CbO!cQ[O'#CoOOQS'#Co'#CoOOQS'#Ck'#CkQVQ[OOOOQS,58|,58|O#TQXO,59OOOQS-E6i-E6iOOQS'#Cp'#CpOOQS1G.j1G.j",
  stateData: "#m~ObOS~ORROTROVPOXQOZRO[RO]RO^RO~OQUORUXTUXVUXXUXZUX[UX]UX^UX`UX~OYVORcXTcXVcXXcXZcX[cX]cX^cX`cX~OPXOZXO[XO]XO~OTV^][ZXY[~",
  goto: "wePPPPPPfPfPPPPPPjPPPptTROTQTORWTTSOTRYV",
  nodeNames: "⚠ ParamValue MessageText BareParamWord Program LineComment Message MessageCommand Param MacroName Operator String Number ParamWord Command",
  maxTerm: 20,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "-w~RhXY!mYZ!m]^!mpq!mrs#Ost#rwx$Z{|$x}!O$x!O!P%R!Q![%a!]!^#r!_!`%l!c!i%q!i!j'x!j!o%q!o!p)f!p!}%q#R#S,T#T#Z%q#Z#['x#[#a%q#a#b)f#b#o%q~!rSb~XY!mYZ!m]^!mpq!m~#TUZ~OY#OZr#Ors#gs;'S#O;'S;=`#l<%lO#O~#lOZ~~#oP;=`<%l#O~#wST~OY#rZ;'S#r;'S;=`$T<%lO#r~$WP;=`<%l#r~$`UZ~OY$ZZw$Zwx#gx;'S$Z;'S;=`$r<%lO$Z~$uP;=`<%l$Z~${Q!O!P%R!Q![%a~%UP!Q![%X~%^P[~!Q![%X~%fQ[~!O!P%X!Q![%a~%qOY~~%vVX~{|&]}!O&]!O!P&f!Q!['P!c!}'g#R#S'g#T#o'g~&`Q!O!P&f!Q![&t~&iP!Q![&l~&qP]~!Q![&l~&yQ]~!O!P&l!Q![&t~'WT]~X~!O!P&l!Q!['P!c!}'g#R#S'g#T#o'g~'lSX~!Q!['g!c!}'g#R#S'g#T#o'g~'}VX~{|&]}!O&]!O!P&f!Q![(d!c!}'g#R#S'g#T#o'g~(mT^~]~X~!O!P(|!Q![(d!c!}'g#R#S'g#T#o'g~)TQ^~]~!O!P)Z!Q![(|~)`Q^~!O!P)Z!Q![)Z~)kXX~{|&]}!O&]!O!P&f!Q!R(d!R!S*W!S![(d!c!}'g#R#S'g#T#o'g~*aV^~]~X~!O!P(|!Q!R(d!R!S*v!S![(d!c!}'g#R#S'g#T#o'g~+PW^~]~X~!O!P(|!Q!X(d!X!Y+i!Y!Z+i!Z![(d!c!}'g#R#S'g#T#o'g~+tTV~^~]~X~!O!P(|!Q![(d!c!}'g#R#S'g#T#o'g~,Y[X~!Q!['g!c!i'g!i!j-O!j!o'g!o!p-O!p!}'g#R#S'g#T#Z'g#Z#[-O#[#a'g#a#b-O#b#o'g~-TSX~!Q![-a!c!}'g#R#S'g#T#o'g~-hT^~X~!O!P)Z!Q![-a!c!}'g#R#S'g#T#o'g",
  tokenizers: [paramValue, messageText, bareParamWord, 0],
  topRules: {"Program":[0,4]},
  tokenPrec: 111
})
