// @ts-nocheck
// GENERATED by scripts/build-grammars.mjs from klipperConfig.grammar — do not edit.
// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  GcodeBody = 1,
  PropertyName = 2,
  ValuePunctuation = 3,
  Comma = 4,
  StringComma = 5,
  Comment = 6,
  ConfigFile = 7,
  SectionHeader = 8,
  SectionType = 10,
  SectionName = 11,
  GcodeProperty = 13,
  GcodeKey = 14,
  Property = 15,
  Number = 16,
  Boolean = 17,
  StringValue = 18,
  QuotedString = 19,
  Operator = 20
