// @ts-nocheck
// GENERATED by scripts/build-grammars.mjs from gcode.grammar — do not edit.
// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {paramValue, messageText} from "./gcode.tokens"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!dQVQSOOOtQUO'#CaO!iQSO'#CpOOQO'#Cp'#CpOOQO'#Cl'#ClQVQSOOOOQO,58{,58{O#^QTO,58}OOQO-E6j-E6jOOQO'#Cq'#CqOOQO1G.i1G.i",
  stateData: "$O~OcOS~OSROUPOWQOYROZRO[RO]RO^RO_RO~OQUOSTXUTXWTXYTXZTX[TX]TX^TX_TXaTX~OXVOSdXUdXWdXYdXZdX[dX]dX^dX_dXadX~OPXOYXOZXO[XO]XO^XO~OSU_]^[ZYWX[~",
  goto: "xfPPPPPgPgPPPPPPPPkPPPquTROTQTORWTTSOTRYV",
  nodeNames: "⚠ ParamValue MessageText Program LineComment Message MessageCommand Param MacroName Operator String Number ParamWord AxisWord FeedWord Command",
  maxTerm: 21,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "1c~R!SXY$_YZ$_]^$_pq$_rs$pst%dwx%{{|&j}!O&j!O!P&s!Q!['R!]!^%d!_!`'^!c!g'c!g!h't!h!i)j!i!j+`!j!k'c!k!l't!l!m't!m!o'c!o!p,d!p!r'c!r!s't!s!u'c!u!v.r!v!w.r!w!z'c!z!{'t!{!|'t!|!}'t#R#S0h#T#X'c#X#Y't#Y#Z)j#Z#[+`#[#]'c#]#^'t#^#_'t#_#a'c#a#b,d#b#d'c#d#e't#e#g'c#g#h.r#h#i.r#i#l'c#l#m't#m#n't#n#o't~$dSc~XY$_YZ$_]^$_pq$_~$uUY~OY$pZr$prs%Xs;'S$p;'S;=`%^<%lO$p~%^OY~~%aP;=`<%l$p~%iSS~OY%dZ;'S%d;'S;=`%u<%lO%d~%xP;=`<%l%d~&QUY~OY%{Zw%{wx%Xx;'S%{;'S;=`&d<%lO%{~&gP;=`<%l%{~&mQ!O!P&s!Q!['R~&vP!Q![&y~'OPZ~!Q![&y~'WQZ~!O!P&y!Q!['R~'cOX~~'hSW~!Q!['c!c!}'c#R#S'c#T#o'c~'yVW~{|(`}!O(`!O!P(i!Q![)S!c!}'c#R#S'c#T#o'c~(cQ!O!P(i!Q![(w~(lP!Q![(o~(tP]~!Q![(o~(|Q]~!O!P(o!Q![(w~)ZT]~W~!O!P(o!Q![)S!c!}'c#R#S'c#T#o'c~)oVW~{|*U}!O*U!O!P*_!Q![*x!c!}'c#R#S'c#T#o'c~*XQ!O!P*_!Q![*m~*bP!Q![*e~*jP^~!Q![*e~*rQ^~!O!P*e!Q![*m~+PT^~W~!O!P*e!Q![*x!c!}'c#R#S'c#T#o'c~+eSW~!Q![+q!c!}'c#R#S'c#T#o'c~+xT_~W~!O!P,X!Q![+q!c!}'c#R#S'c#T#o'c~,^Q_~!O!P,X!Q![,X~,iUW~!Q!R+q!R!S,{!S![+q!c!}'c#R#S'c#T#o'c~-SV_~W~!O!P,X!Q!R+q!R!S-i!S![+q!c!}'c#R#S'c#T#o'c~-pW_~W~!O!P,X!Q!X+q!X!Y.Y!Y!Z.Y!Z![+q!c!}'c#R#S'c#T#o'c~.cTU~_~W~!O!P,X!Q![+q!c!}'c#R#S'c#T#o'c~.wVW~{|/^}!O/^!O!P/g!Q![0Q!c!}'c#R#S'c#T#o'c~/aQ!O!P/g!Q![/u~/jP!Q![/m~/rP[~!Q![/m~/zQ[~!O!P/m!Q![/u~0XT[~W~!O!P/m!Q![0Q!c!}'c#R#S'c#T#o'c~0m[W~!Q!['c!c!i'c!i!j+`!j!o'c!o!p+`!p!}'c#R#S'c#T#Z'c#Z#[+`#[#a'c#a#b+`#b#o'c",
  tokenizers: [paramValue, messageText, 0],
  topRules: {"Program":[0,3]},
  tokenPrec: 126
})
