// @ts-nocheck
// GENERATED by scripts/build-grammars.mjs from gcode.grammar — do not edit.
// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  LineComment = 2,
  Message = 3,
  Command = 4,
  AxisWord = 5,
  FeedWord = 6,
  ParamWord = 7,
  Number = 8,
  String = 9,
  MacroName = 10,
  Operator = 11
