// @ts-nocheck
// GENERATED by scripts/build-grammars.mjs from gcode.grammar — do not edit.
// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {paramValue} from "./gcode.tokens"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!WQVQQOOOtQQO'#CnOOQO'#Cn'#CnOOQO'#Cj'#CjQVQQOOO!iQRO,58{OOQO-E6h-E6hOOQO'#Co'#CoOOQO1G.g1G.g",
  stateData: "#Z~OaOS~ORQOSQOUPOWQOXQOYQOZQO[QO]QO~OVTORbXSbXUbXWbXXbXYbXZbX[bX]bX_bX~OPVOWVOXVOYVOZVO[VO~ORS]Z[YXWUVY~",
  goto: "vdPPPPPePPPPPPPPiPPPosTQOSQSORUSTROSRWT",
  nodeNames: "⚠ ParamValue Program LineComment Message Param MacroName Operator String Number ParamWord AxisWord FeedWord Command",
  maxTerm: 19,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "4T~R!SXY$_YZ$_]^$_pq$_rs$pst%dwx%{{|&j}!O&j!O!P&s!Q!['R!]!^%d!_!`'^!c!g'c!g!h't!h!i)j!i!j+`!j!k'c!k!l't!l!m't!m!o'c!o!p,d!p!r'c!r!s't!s!u'c!u!v1d!v!w1d!w!z'c!z!{'t!{!|'t!|!}'t#R#S3Y#T#X'c#X#Y't#Y#Z)j#Z#[+`#[#]'c#]#^'t#^#_'t#_#a'c#a#b,d#b#d'c#d#e't#e#g'c#g#h1d#h#i1d#i#l'c#l#m't#m#n't#n#o't~$dSa~XY$_YZ$_]^$_pq$_~$uUW~OY$pZr$prs%Xs;'S$p;'S;=`%^<%lO$p~%^OW~~%aP;=`<%l$p~%iSR~OY%dZ;'S%d;'S;=`%u<%lO%d~%xP;=`<%l%d~&QUW~OY%{Zw%{wx%Xx;'S%{;'S;=`&d<%lO%{~&gP;=`<%l%{~&mQ!O!P&s!Q!['R~&vP!Q![&y~'OPX~!Q![&y~'WQX~!O!P&y!Q!['R~'cOV~~'hSU~!Q!['c!c!}'c#R#S'c#T#o'c~'yVU~{|(`}!O(`!O!P(i!Q![)S!c!}'c#R#S'c#T#o'c~(cQ!O!P(i!Q![(w~(lP!Q![(o~(tPZ~!Q![(o~(|QZ~!O!P(o!Q![(w~)ZTZ~U~!O!P(o!Q![)S!c!}'c#R#S'c#T#o'c~)oVU~{|*U}!O*U!O!P*_!Q![*x!c!}'c#R#S'c#T#o'c~*XQ!O!P*_!Q![*m~*bP!Q![*e~*jP[~!Q![*e~*rQ[~!O!P*e!Q![*m~+PT[~U~!O!P*e!Q![*x!c!}'c#R#S'c#T#o'c~+eSU~!Q![+q!c!}'c#R#S'c#T#o'c~+xT]~U~!O!P,X!Q![+q!c!}'c#R#S'c#T#o'c~,^Q]~!O!P,X!Q![,X~,iUU~!Q!R+q!R!S,{!S![+q!c!}'c#R#S'c#T#o'c~-SV]~U~!O!P,X!Q!R+q!R!S-i!S![+q!c!}'c#R#S'c#T#o'c~-pW]~U~!O!P,X!Q!X+q!X!Y.Y!Y!Z.Y!Z![+q!c!}'c#R#S'c#T#o'c~.c^S~]~U~OY/_Z!O/_!O!P/v!P!Q/_!Q![.Y![!c/_!c!}0g!}#R/_#R#S0g#S#T/_#T#o0g#o;'S/_;'S;=`/p<%lO/_~/dSS~OY/_Z;'S/_;'S;=`/p<%lO/_~/sP;=`<%l/_~/}WS~]~OY/_Z!O/_!O!P/v!P!Q/_!Q![/v![;'S/_;'S;=`/p<%lO/_~0n[S~U~OY/_Z!Q/_!Q![0g![!c/_!c!}0g!}#R/_#R#S0g#S#T/_#T#o0g#o;'S/_;'S;=`/p<%lO/_~1iVU~{|2O}!O2O!O!P2X!Q![2r!c!}'c#R#S'c#T#o'c~2RQ!O!P2X!Q![2g~2[P!Q![2_~2dPY~!Q![2_~2lQY~!O!P2_!Q![2g~2yTY~U~!O!P2_!Q![2r!c!}'c#R#S'c#T#o'c~3_[U~!Q!['c!c!i'c!i!j+`!j!o'c!o!p+`!p!}'c#R#S'c#T#Z'c#Z#[+`#[#a'c#a#b+`#b#o'c",
  tokenizers: [paramValue, 0],
  topRules: {"Program":[0,2]},
  tokenPrec: 91
})
