// @ts-nocheck
// GENERATED by scripts/build-grammars.mjs from gcode.grammar — do not edit.
// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "nQVQPOOOOQO'#Cl'#ClOOQO'#Ch'#ChQVQPOOOOQO-E6f-E6f",
  stateData: "!T~O_OS~OQPORPOSPOTPOUPOVPOWPOXPOYPOZPO~OQRSTUVWXYZV~",
  goto: "laPPPPPPPPPPPPbPPPhQRORSRTQOR",
  nodeNames: "⚠ Program LineComment Message Command AxisWord FeedWord ParamWord Number String MacroName Operator",
  maxTerm: 16,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "4T~R!SXY$_YZ$_]^$_pq$_rs$pst%dwx%{{|&j}!O&j!O!P&s!Q!['R!]!^%d!_!`'^!c!g'c!g!h't!h!i)j!i!j+`!j!k'c!k!l't!l!m't!m!o'c!o!p,d!p!r'c!r!s't!s!u'c!u!v1d!v!w1d!w!z'c!z!{'t!{!|'t!|!}'t#R#S3Y#T#X'c#X#Y't#Y#Z)j#Z#[+`#[#]'c#]#^'t#^#_'t#_#a'c#a#b,d#b#d'c#d#e't#e#g'c#g#h1d#h#i1d#i#l'c#l#m't#m#n't#n#o't~$dS_~XY$_YZ$_]^$_pq$_~$uUX~OY$pZr$prs%Xs;'S$p;'S;=`%^<%lO$p~%^OX~~%aP;=`<%l$p~%iSQ~OY%dZ;'S%d;'S;=`%u<%lO%d~%xP;=`<%l%d~&QUX~OY%{Zw%{wx%Xx;'S%{;'S;=`&d<%lO%{~&gP;=`<%l%{~&mQ!O!P&s!Q!['R~&vP!Q![&y~'OPW~!Q![&y~'WQW~!O!P&y!Q!['R~'cOZ~~'hSY~!Q!['c!c!}'c#R#S'c#T#o'c~'yVY~{|(`}!O(`!O!P(i!Q![)S!c!}'c#R#S'c#T#o'c~(cQ!O!P(i!Q![(w~(lP!Q![(o~(tPT~!Q![(o~(|QT~!O!P(o!Q![(w~)ZTT~Y~!O!P(o!Q![)S!c!}'c#R#S'c#T#o'c~)oVY~{|*U}!O*U!O!P*_!Q![*x!c!}'c#R#S'c#T#o'c~*XQ!O!P*_!Q![*m~*bP!Q![*e~*jPU~!Q![*e~*rQU~!O!P*e!Q![*m~+PTU~Y~!O!P*e!Q![*x!c!}'c#R#S'c#T#o'c~+eSY~!Q![+q!c!}'c#R#S'c#T#o'c~+xTS~Y~!O!P,X!Q![+q!c!}'c#R#S'c#T#o'c~,^QS~!O!P,X!Q![,X~,iUY~!Q!R+q!R!S,{!S![+q!c!}'c#R#S'c#T#o'c~-SVS~Y~!O!P,X!Q!R+q!R!S-i!S![+q!c!}'c#R#S'c#T#o'c~-pWS~Y~!O!P,X!Q!X+q!X!Y.Y!Y!Z.Y!Z![+q!c!}'c#R#S'c#T#o'c~.c^R~S~Y~OY/_Z!O/_!O!P/v!P!Q/_!Q![.Y![!c/_!c!}0g!}#R/_#R#S0g#S#T/_#T#o0g#o;'S/_;'S;=`/p<%lO/_~/dSR~OY/_Z;'S/_;'S;=`/p<%lO/_~/sP;=`<%l/_~/}WR~S~OY/_Z!O/_!O!P/v!P!Q/_!Q![/v![;'S/_;'S;=`/p<%lO/_~0n[R~Y~OY/_Z!Q/_!Q![0g![!c/_!c!}0g!}#R/_#R#S0g#S#T/_#T#o0g#o;'S/_;'S;=`/p<%lO/_~1iVY~{|2O}!O2O!O!P2X!Q![2r!c!}'c#R#S'c#T#o'c~2RQ!O!P2X!Q![2g~2[P!Q![2_~2dPV~!Q![2_~2lQV~!O!P2_!Q![2g~2yTV~Y~!O!P2_!Q![2r!c!}'c#R#S'c#T#o'c~3_[Y~!Q!['c!c!i'c!i!j+`!j!o'c!o!p+`!p!}'c#R#S'c#T#Z'c#Z#[+`#[#a'c#a#b+`#b#o'c",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  tokenPrec: 39
})
