// @ts-nocheck
// GENERATED by scripts/build-grammars.mjs from gcode.grammar — do not edit.
// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  ParamValue = 1,
  MessageText = 2,
  Program = 3,
  LineComment = 4,
  Message = 5,
  MessageCommand = 6,
  Param = 7,
  MacroName = 8,
  Operator = 9,
  String = 10,
  Number = 11,
  ParamWord = 12,
  Command = 13
