// @ts-nocheck
// GENERATED by scripts/build-grammars.mjs from gcode.grammar — do not edit.
// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  ParamValue = 1,
  Program = 2,
  LineComment = 3,
  Message = 4,
  Param = 5,
  MacroName = 6,
  Operator = 7,
  String = 8,
  Number = 9,
  ParamWord = 10,
  AxisWord = 11,
  FeedWord = 12,
  Command = 13
