// @ts-nocheck
// GENERATED by scripts/build-grammars.mjs from jinja.grammar — do not edit.
// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Template = 1,
  Text = 2,
  Interpolation = 3,
  InterpolationStart = 4,
  Keyword = 5,
  Boolean = 6,
  Filter = 7,
  Pipe = 8,
  FilterName = 9,
  StringLiteral = 10,
  Number = 11,
  VariableName = 12,
  Operator = 13,
  LineComment = 14,
  InterpolationEnd = 15,
  StatementTag = 16,
  StatementStart = 17,
  StatementEnd = 18,
  Comment = 19
