// @ts-nocheck
// GENERATED by scripts/build-grammars.mjs from klipperConfig.grammar — do not edit.
// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  GcodeBody = 1,
  PropertyName = 2,
  ValuePunctuation = 3,
  Comment = 4,
  ConfigFile = 5,
  SectionHeader = 6,
  SectionType = 8,
  SectionName = 9,
  GcodeProperty = 11,
  GcodeKey = 12,
  Property = 13,
  Number = 14,
  StringValue = 15,
  Comma = 16,
  Operator = 17
