// @ts-nocheck
// GENERATED by scripts/build-grammars.mjs from klipperConfig.grammar — do not edit.
// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  GcodeBody = 1,
  PropertyName = 2,
  Comment = 3,
  ConfigFile = 4,
  SectionHeader = 5,
  SectionType = 7,
  SectionName = 8,
  GcodeProperty = 10,
  GcodeKey = 11,
  Property = 12,
  Number = 13,
  StringValue = 14,
  Comma = 15,
  Operator = 16
