// @ts-nocheck
// GENERATED by scripts/build-grammars.mjs from klipperConfig.grammar — do not edit.
// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  GcodeBody = 1,
  ConfigFile = 2,
  Comment = 3,
  SectionHeader = 4,
  SectionType = 6,
  SectionName = 7,
  GcodeProperty = 9,
  GcodeKey = 10,
  Property = 11,
  PropertyName = 12,
  Number = 13,
  StringValue = 14,
  Comma = 15
