import { styleTags, tags as t } from '@lezer/highlight'

export const klipperConfigHighlighting = styleTags({
    ImportKeyword: t.keyword,
    Import: t.keyword,
    ConfigBlock: t.namespace,
    BlockType: t.namespace,

    Parameter: t.keyword,

    Identifier: t.attributeName,
    Comment: t.lineComment,
    AutoGenerated: t.name,
    Boolean: t.string,
    String: t.string,
    Number: t.number,
    Cords: t.number,
    Pin: t.atom,
    Pins: t.atom,
    VirtualPin: t.atom,
    FilePath: t.className,
    Path: t.className,
    File: t.className,
})
