name: '🏗 debs-cache'

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repo
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules/
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: List the state of node modules
        if: ${{ steps.cache.outputs.cache-hit == 'false' }}
        continue-on-error: true
        run: npm list

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - run: tar -zcf /tmp/mainsail-env.tar.gz .

      - uses: actions/upload-artifact@v3
        with:
          name: workspace
          path: /tmp/mainsail-env.tar.gz
