name: 'Build NEW'

on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow to stop obsolete workflows
concurrency:
  group: ci-tests-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  call-build:
    uses: meteyou/mainsail-dev/.github/workflows/_build.yml@chore/rewrite-workflows
  call-linters:
    uses: meteyou/mainsail-dev/.github/workflows/_linters.yml@chore/rewrite-workflows