name: 'Build NEW'

on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow to stop obsolete workflows
concurrency:
  group: ci-tests-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  debs-cache:
    name: 'Debs-Cache'
    runs-on: ubuntu-latest
    steps:
    - name: Fetch repo
      uses: actions/checkout@v3

    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'

    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules/
        key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

    - name: List the state of node modules
      if: ${{ steps.cache.outputs.cache-hit == 'false' }}
      continue-on-error: true
      run: npm list

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci

  call-build:
    needs: [debs-cache]
    uses: meteyou/mainsail-dev/.github/workflows/_build.yml@chore/rewrite-workflows
  call-linters:
    needs: [debs-cache]
    uses: meteyou/mainsail-dev/.github/workflows/_linters.yml@chore/rewrite-workflows