name: PR target

on:
    pull_request_target:
        types: [synchronize, opened]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# Allow to stop obsolete workflows
concurrency:
    group: ci-tests-${{ github.ref }}-PR
    cancel-in-progress: true

jobs:
    debs-cache:
        runs-on: ubuntu-latest
        steps:
            - name: Debs-Cache
              uses: mainsail-crew/mainsail-actions/debs-cache@master
    check-locale:
        needs: [debs-cache]
        runs-on: ubuntu-latest
        steps:
            - name: Check locale
              uses: mainsail-crew/mainsail-actions/check-locale@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}

    size-report:
        needs: [debs-cache]
        runs-on: ubuntu-latest
        steps:
            - name: Size report
              uses: mainsail-crew/mainsail-actions/size-report@master
