name: Output size check
on: [ pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: preactjs/compressed-size-action@v2
        with:
          pattern: "./dist/**/*.{js,css,html,json}"
          exclude: "{./dist/manifest.json,./dist/build.zip,**/*.map,**/node_modules/**}"